apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  labels:
    app: api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/api:IMAGEVERSION
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
